import React, { useState } from "react";
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogDescription,
} from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import {
  Copy,
  Check,
  Download,
  Terminal,
  FileCode2,
  Sparkles,
  ExternalLink,
  Laptop,
  Cpu,
  Layers,
} from "lucide-react";
import type { BlueprintFile, UserFlowData } from "@/lib/architect-client";

interface ExportRulesModalProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  files: BlueprintFile[];
  ideaTitle: string;
  domain?: string | undefined;
  userFlow?: UserFlowData | null | undefined;
}

export function ExportRulesModal({
  open,
  onOpenChange,
  files,
  ideaTitle,
  domain = "SaaS Platform",
  userFlow,
}: ExportRulesModalProps) {
  const [activeTab, setActiveTab] = useState<"cursorrules" | "cursor_prompt" | "bolt_v0" | "lovable">("cursorrules");
  const [copied, setCopied] = useState(false);

  // 1. Generate customized .cursorrules
  const cursorRulesContent = `# .cursorrules for ${ideaTitle}
# Generated by Pocket CTO (AI Principal Software Architect)

# Project Context
Project: ${ideaTitle}
Domain: ${domain}
Architecture: Full-Stack React + TypeScript + Supabase + Tailwind CSS

# Tech Stack & Standards
- Language: TypeScript 5.8+ (Strict type-checking enabled, no 'any')
- Frontend: React 19, Vite, TanStack Router
- Styling: Tailwind CSS v4 with mobile-first responsive design
- UI Components: Radix UI primitives & Lucide Icons
- Database: Supabase PostgreSQL with Row-Level Security (RLS) policies
- State Management: React Hooks & TanStack Query

# Architectural Principles
1. Complete, Runnable Code Only: Never output placeholder comments like "// TODO" or "// implement here".
2. Non-Destructive Edits: When updating components, preserve existing routes, models, and state variables.
3. Design System Continuity: Adhere strictly to the existing design tokens, typography, and dark/light palettes.
4. Database Security: Always enforce UUID primary keys and RLS policies on all user-facing tables.

# Workspace File Structure
${files.map((f) => `- ${f.name}`).join("\n")}
`;

  // 2. Generate Cursor Composer Master Prompt
  const cursorComposerPrompt = `You are a Principal Software Engineer. Build the complete, full-stack application for: "${ideaTitle}" (${domain}).

Architecture & Navigation Map:
${
  userFlow?.branches
    ? userFlow.branches
        .map((b) => `• Branch [${b.name}]: ${b.steps?.map((s) => s.title).join(" -> ")}`)
        .join("\n")
    : "Follow standard SaaS hierarchy: Auth -> Dashboard -> Domain Feature Modules -> Settings."
}

Generate full production source code following the provided .cursorrules.`;

  // 3. Generate Bolt.new & v0 Prompt
  const boltPrompt = `Create a modern, full-stack web application for "${ideaTitle}" (${domain}) using React, TypeScript, Tailwind CSS, Lucide Icons, and Supabase.

Key Requirements:
- Responsive, modern high-contrast UI (Dark & Light theme support)
- User Authentication flow & protected dashboard layouts
- Complete interactive domain screens with realistic mock data & Supabase hooks
- Clean, accessible modals, command palettes, and tables

Files & Component Structure:
${files.slice(0, 15).map((f) => `- ${f.name}`).join("\n")}
`;

  // 4. Generate Lovable Prompt
  const lovablePrompt = `Build "${ideaTitle}" (${domain}) with high-contrast UI, responsive layouts, and Supabase database integration.

Include:
1. Navigation & Header with theme toggle and user profile.
2. Central Dashboard with domain analytics and quick action cards.
3. Full CRUD features for core business entities with SQL schema.`;

  const activeContent =
    activeTab === "cursorrules"
      ? cursorRulesContent
      : activeTab === "cursor_prompt"
        ? cursorComposerPrompt
        : activeTab === "bolt_v0"
          ? boltPrompt
          : lovablePrompt;

  const handleCopy = () => {
    void navigator.clipboard.writeText(activeContent);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownloadFile = () => {
    const fileName =
      activeTab === "cursorrules"
        ? ".cursorrules"
        : activeTab === "cursor_prompt"
          ? "CURSOR_COMPOSER_PROMPT.md"
          : activeTab === "bolt_v0"
            ? "BOLT_V0_PROMPT.md"
            : "LOVABLE_PROMPT.md";

    const blob = new Blob([activeContent], { type: "text/plain;charset=utf-8" });
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.href = url;
    link.download = fileName;
    link.click();
    URL.revokeObjectURL(url);
  };

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="max-w-2xl border-border bg-[#080d1a] text-foreground p-6 shadow-2xl">
        <DialogHeader className="pb-3 border-b border-border/80">
          <div className="flex items-center gap-3">
            <div className="flex size-9 items-center justify-center rounded-xl bg-gradient-to-br from-primary to-teal-500 text-slate-950 font-bold shadow-md shadow-primary/20">
              <Cpu className="size-5" />
            </div>
            <div>
              <DialogTitle className="font-display text-lg font-bold text-foreground">
                Export AI Rules & Prompt Packs
              </DialogTitle>
              <DialogDescription className="text-xs text-muted-foreground">
                Export tailored system rules and prompt packages for Cursor, Windsurf, Bolt, Lovable, and v0.
              </DialogDescription>
            </div>
          </div>
        </DialogHeader>

        {/* Tab Switcher */}
        <div className="flex items-center gap-1.5 pt-3 overflow-x-auto">
          <button
            onClick={() => setActiveTab("cursorrules")}
            className={`flex items-center gap-1.5 px-3 py-1.5 rounded-lg font-mono text-xs transition-all whitespace-nowrap ${
              activeTab === "cursorrules"
                ? "bg-primary/20 text-primary font-bold border border-primary/40"
                : "text-muted-foreground hover:bg-background/60 hover:text-foreground"
            }`}
          >
            <FileCode2 className="size-3.5 text-teal-400" /> .cursorrules
          </button>

          <button
            onClick={() => setActiveTab("cursor_prompt")}
            className={`flex items-center gap-1.5 px-3 py-1.5 rounded-lg font-mono text-xs transition-all whitespace-nowrap ${
              activeTab === "cursor_prompt"
                ? "bg-purple-500/20 text-purple-300 font-bold border border-purple-500/40"
                : "text-muted-foreground hover:bg-background/60 hover:text-foreground"
            }`}
          >
            <Sparkles className="size-3.5 text-purple-400" /> Cursor / Windsurf Prompt
          </button>

          <button
            onClick={() => setActiveTab("bolt_v0")}
            className={`flex items-center gap-1.5 px-3 py-1.5 rounded-lg font-mono text-xs transition-all whitespace-nowrap ${
              activeTab === "bolt_v0"
                ? "bg-amber-500/20 text-amber-300 font-bold border border-amber-500/40"
                : "text-muted-foreground hover:bg-background/60 hover:text-foreground"
            }`}
          >
            <Laptop className="size-3.5 text-amber-400" /> Bolt.new / v0 Prompt
          </button>

          <button
            onClick={() => setActiveTab("lovable")}
            className={`flex items-center gap-1.5 px-3 py-1.5 rounded-lg font-mono text-xs transition-all whitespace-nowrap ${
              activeTab === "lovable"
                ? "bg-cyan-500/20 text-cyan-300 font-bold border border-cyan-500/40"
                : "text-muted-foreground hover:bg-background/60 hover:text-foreground"
            }`}
          >
            <Layers className="size-3.5 text-cyan-400" /> Lovable Prompt
          </button>
        </div>

        {/* Content Box */}
        <div className="relative rounded-xl border border-border/80 bg-[#050811] p-4 max-h-[320px] overflow-y-auto">
          <pre className="font-mono text-xs leading-relaxed text-slate-200 whitespace-pre-wrap select-all">
            {activeContent}
          </pre>
        </div>

        {/* Action Footer */}
        <div className="flex items-center justify-between pt-3 border-t border-border/60">
          <span className="font-mono text-[11px] text-muted-foreground">
            {activeTab === "cursorrules"
              ? "Place .cursorrules in your repository root directory"
              : "Paste this prompt directly into your AI coding assistant"}
          </span>

          <div className="flex items-center gap-2">
            <Button
              variant="outline"
              size="sm"
              onClick={handleDownloadFile}
              className="h-8 gap-1.5 font-mono text-xs border-border/80 text-foreground hover:bg-background/80"
            >
              <Download className="size-3.5" /> Download File
            </Button>

            <Button
              size="sm"
              onClick={handleCopy}
              className="h-8 gap-1.5 bg-primary font-mono text-xs text-primary-foreground shadow-md hover:opacity-95"
            >
              {copied ? <Check className="size-3.5 text-emerald-300" /> : <Copy className="size-3.5" />}
              {copied ? "Copied!" : "Copy to Clipboard"}
            </Button>
          </div>
        </div>
      </DialogContent>
    </Dialog>
  );
}
