/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as ApiBlueprintRouteImport } from './routes/api/blueprint'
import { Route as ApiPhasesRouteImport } from './routes/api/phases'
import { Route as ApiSurveyRouteImport } from './routes/api/survey'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBlueprintRoute = ApiBlueprintRouteImport.update({
  id: '/api/blueprint',
  path: '/api/blueprint',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPhasesRoute = ApiPhasesRouteImport.update({
  id: '/api/phases',
  path: '/api/phases',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSurveyRoute = ApiSurveyRouteImport.update({
  id: '/api/survey',
  path: '/api/survey',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/history': typeof HistoryRoute
  '/api/blueprint': typeof ApiBlueprintRoute
  '/api/phases': typeof ApiPhasesRoute
  '/api/survey': typeof ApiSurveyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/history': typeof HistoryRoute
  '/api/blueprint': typeof ApiBlueprintRoute
  '/api/phases': typeof ApiPhasesRoute
  '/api/survey': typeof ApiSurveyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/history': typeof HistoryRoute
  '/api/blueprint': typeof ApiBlueprintRoute
  '/api/phases': typeof ApiPhasesRoute
  '/api/survey': typeof ApiSurveyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/history'
    | '/api/blueprint'
    | '/api/phases'
    | '/api/survey'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/history'
    | '/api/blueprint'
    | '/api/phases'
    | '/api/survey'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/history'
    | '/api/blueprint'
    | '/api/phases'
    | '/api/survey'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  HistoryRoute: typeof HistoryRoute
  ApiBlueprintRoute: typeof ApiBlueprintRoute
  ApiPhasesRoute: typeof ApiPhasesRoute
  ApiSurveyRoute: typeof ApiSurveyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/blueprint': {
      id: '/api/blueprint'
      path: '/api/blueprint'
      fullPath: '/api/blueprint'
      preLoaderRoute: typeof ApiBlueprintRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/phases': {
      id: '/api/phases'
      path: '/api/phases'
      fullPath: '/api/phases'
      preLoaderRoute: typeof ApiPhasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/survey': {
      id: '/api/survey'
      path: '/api/survey'
      fullPath: '/api/survey'
      preLoaderRoute: typeof ApiSurveyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  HistoryRoute: HistoryRoute,
  ApiBlueprintRoute: ApiBlueprintRoute,
  ApiPhasesRoute: ApiPhasesRoute,
  ApiSurveyRoute: ApiSurveyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
