/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiBlueprintRouteImport } from './routes/api/blueprint'
import { Route as ApiPingRouteImport } from './routes/api/ping'
import { Route as ApiPing2RouteImport } from './routes/api/ping2'
import { Route as ApiSurveyRouteImport } from './routes/api/survey'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBlueprintRoute = ApiBlueprintRouteImport.update({
  id: '/api/blueprint',
  path: '/api/blueprint',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPingRoute = ApiPingRouteImport.update({
  id: '/api/ping',
  path: '/api/ping',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPing2Route = ApiPing2RouteImport.update({
  id: '/api/ping2',
  path: '/api/ping2',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSurveyRoute = ApiSurveyRouteImport.update({
  id: '/api/survey',
  path: '/api/survey',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/blueprint': typeof ApiBlueprintRoute
  '/api/ping': typeof ApiPingRoute
  '/api/ping2': typeof ApiPing2Route
  '/api/survey': typeof ApiSurveyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/blueprint': typeof ApiBlueprintRoute
  '/api/ping': typeof ApiPingRoute
  '/api/ping2': typeof ApiPing2Route
  '/api/survey': typeof ApiSurveyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/blueprint': typeof ApiBlueprintRoute
  '/api/ping': typeof ApiPingRoute
  '/api/ping2': typeof ApiPing2Route
  '/api/survey': typeof ApiSurveyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/blueprint' | '/api/ping' | '/api/ping2' | '/api/survey'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/blueprint' | '/api/ping' | '/api/ping2' | '/api/survey'
  id:
    | '__root__'
    | '/'
    | '/api/blueprint'
    | '/api/ping'
    | '/api/ping2'
    | '/api/survey'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiBlueprintRoute: typeof ApiBlueprintRoute
  ApiPingRoute: typeof ApiPingRoute
  ApiPing2Route: typeof ApiPing2Route
  ApiSurveyRoute: typeof ApiSurveyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/blueprint': {
      id: '/api/blueprint'
      path: '/api/blueprint'
      fullPath: '/api/blueprint'
      preLoaderRoute: typeof ApiBlueprintRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ping': {
      id: '/api/ping'
      path: '/api/ping'
      fullPath: '/api/ping'
      preLoaderRoute: typeof ApiPingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ping2': {
      id: '/api/ping2'
      path: '/api/ping2'
      fullPath: '/api/ping2'
      preLoaderRoute: typeof ApiPing2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/survey': {
      id: '/api/survey'
      path: '/api/survey'
      fullPath: '/api/survey'
      preLoaderRoute: typeof ApiSurveyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiBlueprintRoute: ApiBlueprintRoute,
  ApiPingRoute: ApiPingRoute,
  ApiPing2Route: ApiPing2Route,
  ApiSurveyRoute: ApiSurveyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
